apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: users-service
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/team-tech-challenge/tech-challenge-manifest.git'
    targetRevision: HEAD
    path: users-service/kustomize/overlays/prd
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-users-service
  syncPolicy:
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
revisionHistoryLimit: 5
